language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

script:
  - ./gradlew build check
